### ISSUE TITLE
this is like flexiblegs formula?

### ISSUE THREAD

**Issue by dnomak** [inuitcss/tools.widths#1]
flexiblegs column mixin https://github.com/flexiblegs/flexiblegs/blob/master/dynamic/sass/scss/flexiblegs/flexiblegs/mixins/_col.scss and tweet https://twitter.com/flexiblegs/status/550265997639573504 :)

**Comment by csswizardry** [comment]
It’s not like anything, I don’t think. It’s super scrappy so I’m hoping someone Sassy might be able to tidy it up: https://github.com/inuitcss/trumps.widths/issues/11
