### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/tools.widths#11]
This is not really a problem but I want to point out that this package doesn't follow the same naming convention (bower, npm):
- tools.widths : inuit-tools-widths > inuit-widths-tools
- trumps.widths : inuit-widths
- trumps.widths-responsive : inuit-widths-responsive

**Comment by anselmh** [comment]
Yup, but this shouldn’t be fixed as it means deprecating the package at npm and therefore is not recommended.

**Comment by florianbouvot** [comment]
I understand.
