### ISSUE TITLE
Use `to` instead of `throughout` for generating widths

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/tools.widths#2]
On [this line](https://github.com/inuitcss/tools.widths/blob/master/_tools.widths.scss#L33). Otherwise you get classes like `.2/2`, `.3/3`, `.4/4` etc :)

**Comment by Crawleyprint** [comment]
@nenadjelovac class name convention `.x/x` could be there to preserve the context, e.g. working in halfs, thirds, tenths. @csswizardry ?

**Comment by csswizardry** [comment]
Hmm. Interesting one. There will be times when we want a full-width item, so `.u-1/1` is desired, but do you think we just hard-code `.u-1/1` and then stop the fractions at `.u-5/6` (for example)?

**Comment by nenadjelovac** [comment]
Yes, we want 1/1, but only that one. This should do it -> http://sassmeister.com/gist/8f593a6af40ac9b34d05.

**Comment by csswizardry** [comment]
Dude that’s perfect, thank you! I’m porting this in now :D

**Comment by nenadjelovac** [comment]
Great! And no problem ;)

**Comment by csswizardry** [comment]
@nenadjelovac Please can you cast an eye over #4 and merge it in if it looks okay?

**Comment by nenadjelovac** [comment]
That's it @csswizardry. You can go ahead and merge.

**Comment by nenadjelovac** [comment]
Closed via https://github.com/inuitcss/tools.widths/commit/41fca80c0e836dd77b8f3ea63dece3b948f77bcd
